local:
	go run main.go -address 127.0.0.1:52898
	go run main.go -serverAddress localhost:52898
online:
	go run main.go -address 34.143.228.170:8080
url:
	go run main.go -address esystemci.fortress-asya.com:8080
.PHONY: local online

