// Code generated by sqlc. DO NOT EDIT.

package dwhcb

import (
	"context"
)

type QuerierCustomer interface {

	GetCustomerInfo(ctx context.Context, id int64) (CustomerInfo, error)
	ListCustomer(ctx context.Context, arg ListCustomerParams) ([]CustomerInfo, error)
}

var _ QuerierCustomer = (*QueriesCustomer)(nil)
