// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// DumpServiceClient is the client API for DumpService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DumpServiceClient interface {
	GetModifiedTable(ctx context.Context, in *GetModifiedTableRequest, opts ...grpc.CallOption) (DumpService_GetModifiedTableClient, error)
	GetDumpBranchList(ctx context.Context, in *GetDumpBranchListRequest, opts ...grpc.CallOption) (*DumpBranchList, error)
	ListDumpBranchList(ctx context.Context, in *NoParam, opts ...grpc.CallOption) (DumpService_ListDumpBranchListClient, error)
	CreateDumpBranchList(ctx context.Context, in *CreateDumpBranchListRequest, opts ...grpc.CallOption) (*CreateDumpBranchListResponse, error)
	UpdateDumpBranchList(ctx context.Context, in *UpdateDumpBranchListRequest, opts ...grpc.CallOption) (*UpdateDumpBranchListResponse, error)
	CreateDumpArea(ctx context.Context, opts ...grpc.CallOption) (DumpService_CreateDumpAreaClient, error)
	CreateDumpUnit(ctx context.Context, opts ...grpc.CallOption) (DumpService_CreateDumpUnitClient, error)
	CreateDumpCenter(ctx context.Context, opts ...grpc.CallOption) (DumpService_CreateDumpCenterClient, error)
	CreateDumpCustomer(ctx context.Context, opts ...grpc.CallOption) (DumpService_CreateDumpCustomerClient, error)
	CreateDumpAddresses(ctx context.Context, opts ...grpc.CallOption) (DumpService_CreateDumpAddressesClient, error)
	CreateDumpLnMaster(ctx context.Context, opts ...grpc.CallOption) (DumpService_CreateDumpLnMasterClient, error)
	CreateDumpSaMaster(ctx context.Context, opts ...grpc.CallOption) (DumpService_CreateDumpSaMasterClient, error)
	CreateDumpTrnMaster(ctx context.Context, opts ...grpc.CallOption) (DumpService_CreateDumpTrnMasterClient, error)
	CreateDumpSaTrnMaster(ctx context.Context, opts ...grpc.CallOption) (DumpService_CreateDumpSaTrnMasterClient, error)
	CreateDumpLoanInst(ctx context.Context, opts ...grpc.CallOption) (DumpService_CreateDumpLoanInstClient, error)
	CreateDumpLnChrgData(ctx context.Context, opts ...grpc.CallOption) (DumpService_CreateDumpLnChrgDataClient, error)
	CreateDumpCustAddInfoGroup(ctx context.Context, opts ...grpc.CallOption) (DumpService_CreateDumpCustAddInfoGroupClient, error)
	CreateDumpCustAddInfoList(ctx context.Context, opts ...grpc.CallOption) (DumpService_CreateDumpCustAddInfoListClient, error)
	CreateDumpCustAddInfoGroupNeed(ctx context.Context, opts ...grpc.CallOption) (DumpService_CreateDumpCustAddInfoGroupNeedClient, error)
	CreateDumpCustAddInfo(ctx context.Context, opts ...grpc.CallOption) (DumpService_CreateDumpCustAddInfoClient, error)
	CreateDumpMutualFund(ctx context.Context, opts ...grpc.CallOption) (DumpService_CreateDumpMutualFundClient, error)
	CreateDumpReferencesDetails(ctx context.Context, opts ...grpc.CallOption) (DumpService_CreateDumpReferencesDetailsClient, error)
	CreateDumpCenterWorker(ctx context.Context, opts ...grpc.CallOption) (DumpService_CreateDumpCenterWorkerClient, error)
	CreateDumpWriteoff(ctx context.Context, opts ...grpc.CallOption) (DumpService_CreateDumpWriteoffClient, error)
	CreateDumpAccounts(ctx context.Context, opts ...grpc.CallOption) (DumpService_CreateDumpAccountsClient, error)
	CreateDumpJnlDetails(ctx context.Context, opts ...grpc.CallOption) (DumpService_CreateDumpJnlDetailsClient, error)
	CreateDumpJnlHeaders(ctx context.Context, opts ...grpc.CallOption) (DumpService_CreateDumpJnlHeadersClient, error)
	CreateDumpLedgerDetails(ctx context.Context, opts ...grpc.CallOption) (DumpService_CreateDumpLedgerDetailsClient, error)
	CreateDumpUsersList(ctx context.Context, opts ...grpc.CallOption) (DumpService_CreateDumpUsersListClient, error)
	CreateDumpMultiplePaymentReceipt(ctx context.Context, opts ...grpc.CallOption) (DumpService_CreateDumpMultiplePaymentReceiptClient, error)
	CreateDumpInActiveCID(ctx context.Context, opts ...grpc.CallOption) (DumpService_CreateDumpInActiveCIDClient, error)
	CreateDumpLnBeneficiary(ctx context.Context, opts ...grpc.CallOption) (DumpService_CreateDumpLnBeneficiaryClient, error)
	CreateDumpReactivateWriteoff(ctx context.Context, opts ...grpc.CallOption) (DumpService_CreateDumpReactivateWriteoffClient, error)
	CreateDumpColSht(ctx context.Context, opts ...grpc.CallOption) (DumpService_CreateDumpColShtClient, error)
	GetDumpColSht(ctx context.Context, opts ...grpc.CallOption) (DumpService_GetDumpColShtClient, error)
}

type dumpServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDumpServiceClient(cc grpc.ClientConnInterface) DumpServiceClient {
	return &dumpServiceClient{cc}
}

func (c *dumpServiceClient) GetModifiedTable(ctx context.Context, in *GetModifiedTableRequest, opts ...grpc.CallOption) (DumpService_GetModifiedTableClient, error) {
	stream, err := c.cc.NewStream(ctx, &DumpService_ServiceDesc.Streams[0], "/simplebank.DumpService/GetModifiedTable", opts...)
	if err != nil {
		return nil, err
	}
	x := &dumpServiceGetModifiedTableClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type DumpService_GetModifiedTableClient interface {
	Recv() (*DumpModifiedTable, error)
	grpc.ClientStream
}

type dumpServiceGetModifiedTableClient struct {
	grpc.ClientStream
}

func (x *dumpServiceGetModifiedTableClient) Recv() (*DumpModifiedTable, error) {
	m := new(DumpModifiedTable)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *dumpServiceClient) GetDumpBranchList(ctx context.Context, in *GetDumpBranchListRequest, opts ...grpc.CallOption) (*DumpBranchList, error) {
	out := new(DumpBranchList)
	err := c.cc.Invoke(ctx, "/simplebank.DumpService/GetDumpBranchList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dumpServiceClient) ListDumpBranchList(ctx context.Context, in *NoParam, opts ...grpc.CallOption) (DumpService_ListDumpBranchListClient, error) {
	stream, err := c.cc.NewStream(ctx, &DumpService_ServiceDesc.Streams[1], "/simplebank.DumpService/ListDumpBranchList", opts...)
	if err != nil {
		return nil, err
	}
	x := &dumpServiceListDumpBranchListClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type DumpService_ListDumpBranchListClient interface {
	Recv() (*DumpBranchList, error)
	grpc.ClientStream
}

type dumpServiceListDumpBranchListClient struct {
	grpc.ClientStream
}

func (x *dumpServiceListDumpBranchListClient) Recv() (*DumpBranchList, error) {
	m := new(DumpBranchList)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *dumpServiceClient) CreateDumpBranchList(ctx context.Context, in *CreateDumpBranchListRequest, opts ...grpc.CallOption) (*CreateDumpBranchListResponse, error) {
	out := new(CreateDumpBranchListResponse)
	err := c.cc.Invoke(ctx, "/simplebank.DumpService/CreateDumpBranchList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dumpServiceClient) UpdateDumpBranchList(ctx context.Context, in *UpdateDumpBranchListRequest, opts ...grpc.CallOption) (*UpdateDumpBranchListResponse, error) {
	out := new(UpdateDumpBranchListResponse)
	err := c.cc.Invoke(ctx, "/simplebank.DumpService/UpdateDumpBranchList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dumpServiceClient) CreateDumpArea(ctx context.Context, opts ...grpc.CallOption) (DumpService_CreateDumpAreaClient, error) {
	stream, err := c.cc.NewStream(ctx, &DumpService_ServiceDesc.Streams[2], "/simplebank.DumpService/CreateDumpArea", opts...)
	if err != nil {
		return nil, err
	}
	x := &dumpServiceCreateDumpAreaClient{stream}
	return x, nil
}

type DumpService_CreateDumpAreaClient interface {
	Send(*CreateDumpAreaRequest) error
	Recv() (*CreateDumpAreaResponse, error)
	grpc.ClientStream
}

type dumpServiceCreateDumpAreaClient struct {
	grpc.ClientStream
}

func (x *dumpServiceCreateDumpAreaClient) Send(m *CreateDumpAreaRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *dumpServiceCreateDumpAreaClient) Recv() (*CreateDumpAreaResponse, error) {
	m := new(CreateDumpAreaResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *dumpServiceClient) CreateDumpUnit(ctx context.Context, opts ...grpc.CallOption) (DumpService_CreateDumpUnitClient, error) {
	stream, err := c.cc.NewStream(ctx, &DumpService_ServiceDesc.Streams[3], "/simplebank.DumpService/CreateDumpUnit", opts...)
	if err != nil {
		return nil, err
	}
	x := &dumpServiceCreateDumpUnitClient{stream}
	return x, nil
}

type DumpService_CreateDumpUnitClient interface {
	Send(*CreateDumpUnitRequest) error
	Recv() (*CreateDumpUnitResponse, error)
	grpc.ClientStream
}

type dumpServiceCreateDumpUnitClient struct {
	grpc.ClientStream
}

func (x *dumpServiceCreateDumpUnitClient) Send(m *CreateDumpUnitRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *dumpServiceCreateDumpUnitClient) Recv() (*CreateDumpUnitResponse, error) {
	m := new(CreateDumpUnitResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *dumpServiceClient) CreateDumpCenter(ctx context.Context, opts ...grpc.CallOption) (DumpService_CreateDumpCenterClient, error) {
	stream, err := c.cc.NewStream(ctx, &DumpService_ServiceDesc.Streams[4], "/simplebank.DumpService/CreateDumpCenter", opts...)
	if err != nil {
		return nil, err
	}
	x := &dumpServiceCreateDumpCenterClient{stream}
	return x, nil
}

type DumpService_CreateDumpCenterClient interface {
	Send(*CreateDumpCenterRequest) error
	Recv() (*CreateDumpCenterResponse, error)
	grpc.ClientStream
}

type dumpServiceCreateDumpCenterClient struct {
	grpc.ClientStream
}

func (x *dumpServiceCreateDumpCenterClient) Send(m *CreateDumpCenterRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *dumpServiceCreateDumpCenterClient) Recv() (*CreateDumpCenterResponse, error) {
	m := new(CreateDumpCenterResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *dumpServiceClient) CreateDumpCustomer(ctx context.Context, opts ...grpc.CallOption) (DumpService_CreateDumpCustomerClient, error) {
	stream, err := c.cc.NewStream(ctx, &DumpService_ServiceDesc.Streams[5], "/simplebank.DumpService/CreateDumpCustomer", opts...)
	if err != nil {
		return nil, err
	}
	x := &dumpServiceCreateDumpCustomerClient{stream}
	return x, nil
}

type DumpService_CreateDumpCustomerClient interface {
	Send(*CreateDumpCustomerRequest) error
	Recv() (*CreateDumpCustomerResponse, error)
	grpc.ClientStream
}

type dumpServiceCreateDumpCustomerClient struct {
	grpc.ClientStream
}

func (x *dumpServiceCreateDumpCustomerClient) Send(m *CreateDumpCustomerRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *dumpServiceCreateDumpCustomerClient) Recv() (*CreateDumpCustomerResponse, error) {
	m := new(CreateDumpCustomerResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *dumpServiceClient) CreateDumpAddresses(ctx context.Context, opts ...grpc.CallOption) (DumpService_CreateDumpAddressesClient, error) {
	stream, err := c.cc.NewStream(ctx, &DumpService_ServiceDesc.Streams[6], "/simplebank.DumpService/CreateDumpAddresses", opts...)
	if err != nil {
		return nil, err
	}
	x := &dumpServiceCreateDumpAddressesClient{stream}
	return x, nil
}

type DumpService_CreateDumpAddressesClient interface {
	Send(*CreateDumpAddressesRequest) error
	Recv() (*CreateDumpAddressesResponse, error)
	grpc.ClientStream
}

type dumpServiceCreateDumpAddressesClient struct {
	grpc.ClientStream
}

func (x *dumpServiceCreateDumpAddressesClient) Send(m *CreateDumpAddressesRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *dumpServiceCreateDumpAddressesClient) Recv() (*CreateDumpAddressesResponse, error) {
	m := new(CreateDumpAddressesResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *dumpServiceClient) CreateDumpLnMaster(ctx context.Context, opts ...grpc.CallOption) (DumpService_CreateDumpLnMasterClient, error) {
	stream, err := c.cc.NewStream(ctx, &DumpService_ServiceDesc.Streams[7], "/simplebank.DumpService/CreateDumpLnMaster", opts...)
	if err != nil {
		return nil, err
	}
	x := &dumpServiceCreateDumpLnMasterClient{stream}
	return x, nil
}

type DumpService_CreateDumpLnMasterClient interface {
	Send(*CreateDumpLnMasterRequest) error
	Recv() (*CreateDumpLnMasterResponse, error)
	grpc.ClientStream
}

type dumpServiceCreateDumpLnMasterClient struct {
	grpc.ClientStream
}

func (x *dumpServiceCreateDumpLnMasterClient) Send(m *CreateDumpLnMasterRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *dumpServiceCreateDumpLnMasterClient) Recv() (*CreateDumpLnMasterResponse, error) {
	m := new(CreateDumpLnMasterResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *dumpServiceClient) CreateDumpSaMaster(ctx context.Context, opts ...grpc.CallOption) (DumpService_CreateDumpSaMasterClient, error) {
	stream, err := c.cc.NewStream(ctx, &DumpService_ServiceDesc.Streams[8], "/simplebank.DumpService/CreateDumpSaMaster", opts...)
	if err != nil {
		return nil, err
	}
	x := &dumpServiceCreateDumpSaMasterClient{stream}
	return x, nil
}

type DumpService_CreateDumpSaMasterClient interface {
	Send(*CreateDumpSaMasterRequest) error
	Recv() (*CreateDumpSaMasterResponse, error)
	grpc.ClientStream
}

type dumpServiceCreateDumpSaMasterClient struct {
	grpc.ClientStream
}

func (x *dumpServiceCreateDumpSaMasterClient) Send(m *CreateDumpSaMasterRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *dumpServiceCreateDumpSaMasterClient) Recv() (*CreateDumpSaMasterResponse, error) {
	m := new(CreateDumpSaMasterResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *dumpServiceClient) CreateDumpTrnMaster(ctx context.Context, opts ...grpc.CallOption) (DumpService_CreateDumpTrnMasterClient, error) {
	stream, err := c.cc.NewStream(ctx, &DumpService_ServiceDesc.Streams[9], "/simplebank.DumpService/CreateDumpTrnMaster", opts...)
	if err != nil {
		return nil, err
	}
	x := &dumpServiceCreateDumpTrnMasterClient{stream}
	return x, nil
}

type DumpService_CreateDumpTrnMasterClient interface {
	Send(*CreateDumpTrnMasterRequest) error
	Recv() (*CreateDumpTrnMasterResponse, error)
	grpc.ClientStream
}

type dumpServiceCreateDumpTrnMasterClient struct {
	grpc.ClientStream
}

func (x *dumpServiceCreateDumpTrnMasterClient) Send(m *CreateDumpTrnMasterRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *dumpServiceCreateDumpTrnMasterClient) Recv() (*CreateDumpTrnMasterResponse, error) {
	m := new(CreateDumpTrnMasterResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *dumpServiceClient) CreateDumpSaTrnMaster(ctx context.Context, opts ...grpc.CallOption) (DumpService_CreateDumpSaTrnMasterClient, error) {
	stream, err := c.cc.NewStream(ctx, &DumpService_ServiceDesc.Streams[10], "/simplebank.DumpService/CreateDumpSaTrnMaster", opts...)
	if err != nil {
		return nil, err
	}
	x := &dumpServiceCreateDumpSaTrnMasterClient{stream}
	return x, nil
}

type DumpService_CreateDumpSaTrnMasterClient interface {
	Send(*CreateDumpSaTrnMasterRequest) error
	Recv() (*CreateDumpSaTrnMasterResponse, error)
	grpc.ClientStream
}

type dumpServiceCreateDumpSaTrnMasterClient struct {
	grpc.ClientStream
}

func (x *dumpServiceCreateDumpSaTrnMasterClient) Send(m *CreateDumpSaTrnMasterRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *dumpServiceCreateDumpSaTrnMasterClient) Recv() (*CreateDumpSaTrnMasterResponse, error) {
	m := new(CreateDumpSaTrnMasterResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *dumpServiceClient) CreateDumpLoanInst(ctx context.Context, opts ...grpc.CallOption) (DumpService_CreateDumpLoanInstClient, error) {
	stream, err := c.cc.NewStream(ctx, &DumpService_ServiceDesc.Streams[11], "/simplebank.DumpService/CreateDumpLoanInst", opts...)
	if err != nil {
		return nil, err
	}
	x := &dumpServiceCreateDumpLoanInstClient{stream}
	return x, nil
}

type DumpService_CreateDumpLoanInstClient interface {
	Send(*CreateDumpLoanInstRequest) error
	Recv() (*CreateDumpLoanInstResponse, error)
	grpc.ClientStream
}

type dumpServiceCreateDumpLoanInstClient struct {
	grpc.ClientStream
}

func (x *dumpServiceCreateDumpLoanInstClient) Send(m *CreateDumpLoanInstRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *dumpServiceCreateDumpLoanInstClient) Recv() (*CreateDumpLoanInstResponse, error) {
	m := new(CreateDumpLoanInstResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *dumpServiceClient) CreateDumpLnChrgData(ctx context.Context, opts ...grpc.CallOption) (DumpService_CreateDumpLnChrgDataClient, error) {
	stream, err := c.cc.NewStream(ctx, &DumpService_ServiceDesc.Streams[12], "/simplebank.DumpService/CreateDumpLnChrgData", opts...)
	if err != nil {
		return nil, err
	}
	x := &dumpServiceCreateDumpLnChrgDataClient{stream}
	return x, nil
}

type DumpService_CreateDumpLnChrgDataClient interface {
	Send(*CreateDumpLnChrgDataRequest) error
	Recv() (*CreateDumpLnChrgDataResponse, error)
	grpc.ClientStream
}

type dumpServiceCreateDumpLnChrgDataClient struct {
	grpc.ClientStream
}

func (x *dumpServiceCreateDumpLnChrgDataClient) Send(m *CreateDumpLnChrgDataRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *dumpServiceCreateDumpLnChrgDataClient) Recv() (*CreateDumpLnChrgDataResponse, error) {
	m := new(CreateDumpLnChrgDataResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *dumpServiceClient) CreateDumpCustAddInfoGroup(ctx context.Context, opts ...grpc.CallOption) (DumpService_CreateDumpCustAddInfoGroupClient, error) {
	stream, err := c.cc.NewStream(ctx, &DumpService_ServiceDesc.Streams[13], "/simplebank.DumpService/CreateDumpCustAddInfoGroup", opts...)
	if err != nil {
		return nil, err
	}
	x := &dumpServiceCreateDumpCustAddInfoGroupClient{stream}
	return x, nil
}

type DumpService_CreateDumpCustAddInfoGroupClient interface {
	Send(*CreateDumpCustAddInfoGroupRequest) error
	Recv() (*CreateDumpCustAddInfoGroupResponse, error)
	grpc.ClientStream
}

type dumpServiceCreateDumpCustAddInfoGroupClient struct {
	grpc.ClientStream
}

func (x *dumpServiceCreateDumpCustAddInfoGroupClient) Send(m *CreateDumpCustAddInfoGroupRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *dumpServiceCreateDumpCustAddInfoGroupClient) Recv() (*CreateDumpCustAddInfoGroupResponse, error) {
	m := new(CreateDumpCustAddInfoGroupResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *dumpServiceClient) CreateDumpCustAddInfoList(ctx context.Context, opts ...grpc.CallOption) (DumpService_CreateDumpCustAddInfoListClient, error) {
	stream, err := c.cc.NewStream(ctx, &DumpService_ServiceDesc.Streams[14], "/simplebank.DumpService/CreateDumpCustAddInfoList", opts...)
	if err != nil {
		return nil, err
	}
	x := &dumpServiceCreateDumpCustAddInfoListClient{stream}
	return x, nil
}

type DumpService_CreateDumpCustAddInfoListClient interface {
	Send(*CreateDumpCustAddInfoListRequest) error
	Recv() (*CreateDumpCustAddInfoListResponse, error)
	grpc.ClientStream
}

type dumpServiceCreateDumpCustAddInfoListClient struct {
	grpc.ClientStream
}

func (x *dumpServiceCreateDumpCustAddInfoListClient) Send(m *CreateDumpCustAddInfoListRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *dumpServiceCreateDumpCustAddInfoListClient) Recv() (*CreateDumpCustAddInfoListResponse, error) {
	m := new(CreateDumpCustAddInfoListResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *dumpServiceClient) CreateDumpCustAddInfoGroupNeed(ctx context.Context, opts ...grpc.CallOption) (DumpService_CreateDumpCustAddInfoGroupNeedClient, error) {
	stream, err := c.cc.NewStream(ctx, &DumpService_ServiceDesc.Streams[15], "/simplebank.DumpService/CreateDumpCustAddInfoGroupNeed", opts...)
	if err != nil {
		return nil, err
	}
	x := &dumpServiceCreateDumpCustAddInfoGroupNeedClient{stream}
	return x, nil
}

type DumpService_CreateDumpCustAddInfoGroupNeedClient interface {
	Send(*CreateDumpCustAddInfoGroupNeedRequest) error
	Recv() (*CreateDumpCustAddInfoGroupNeedResponse, error)
	grpc.ClientStream
}

type dumpServiceCreateDumpCustAddInfoGroupNeedClient struct {
	grpc.ClientStream
}

func (x *dumpServiceCreateDumpCustAddInfoGroupNeedClient) Send(m *CreateDumpCustAddInfoGroupNeedRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *dumpServiceCreateDumpCustAddInfoGroupNeedClient) Recv() (*CreateDumpCustAddInfoGroupNeedResponse, error) {
	m := new(CreateDumpCustAddInfoGroupNeedResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *dumpServiceClient) CreateDumpCustAddInfo(ctx context.Context, opts ...grpc.CallOption) (DumpService_CreateDumpCustAddInfoClient, error) {
	stream, err := c.cc.NewStream(ctx, &DumpService_ServiceDesc.Streams[16], "/simplebank.DumpService/CreateDumpCustAddInfo", opts...)
	if err != nil {
		return nil, err
	}
	x := &dumpServiceCreateDumpCustAddInfoClient{stream}
	return x, nil
}

type DumpService_CreateDumpCustAddInfoClient interface {
	Send(*CreateDumpCustAddInfoRequest) error
	Recv() (*CreateDumpCustAddInfoResponse, error)
	grpc.ClientStream
}

type dumpServiceCreateDumpCustAddInfoClient struct {
	grpc.ClientStream
}

func (x *dumpServiceCreateDumpCustAddInfoClient) Send(m *CreateDumpCustAddInfoRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *dumpServiceCreateDumpCustAddInfoClient) Recv() (*CreateDumpCustAddInfoResponse, error) {
	m := new(CreateDumpCustAddInfoResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *dumpServiceClient) CreateDumpMutualFund(ctx context.Context, opts ...grpc.CallOption) (DumpService_CreateDumpMutualFundClient, error) {
	stream, err := c.cc.NewStream(ctx, &DumpService_ServiceDesc.Streams[17], "/simplebank.DumpService/CreateDumpMutualFund", opts...)
	if err != nil {
		return nil, err
	}
	x := &dumpServiceCreateDumpMutualFundClient{stream}
	return x, nil
}

type DumpService_CreateDumpMutualFundClient interface {
	Send(*CreateDumpMutualFundRequest) error
	Recv() (*CreateDumpMutualFundResponse, error)
	grpc.ClientStream
}

type dumpServiceCreateDumpMutualFundClient struct {
	grpc.ClientStream
}

func (x *dumpServiceCreateDumpMutualFundClient) Send(m *CreateDumpMutualFundRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *dumpServiceCreateDumpMutualFundClient) Recv() (*CreateDumpMutualFundResponse, error) {
	m := new(CreateDumpMutualFundResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *dumpServiceClient) CreateDumpReferencesDetails(ctx context.Context, opts ...grpc.CallOption) (DumpService_CreateDumpReferencesDetailsClient, error) {
	stream, err := c.cc.NewStream(ctx, &DumpService_ServiceDesc.Streams[18], "/simplebank.DumpService/CreateDumpReferencesDetails", opts...)
	if err != nil {
		return nil, err
	}
	x := &dumpServiceCreateDumpReferencesDetailsClient{stream}
	return x, nil
}

type DumpService_CreateDumpReferencesDetailsClient interface {
	Send(*CreateDumpReferencesDetailsRequest) error
	Recv() (*CreateDumpReferencesDetailsResponse, error)
	grpc.ClientStream
}

type dumpServiceCreateDumpReferencesDetailsClient struct {
	grpc.ClientStream
}

func (x *dumpServiceCreateDumpReferencesDetailsClient) Send(m *CreateDumpReferencesDetailsRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *dumpServiceCreateDumpReferencesDetailsClient) Recv() (*CreateDumpReferencesDetailsResponse, error) {
	m := new(CreateDumpReferencesDetailsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *dumpServiceClient) CreateDumpCenterWorker(ctx context.Context, opts ...grpc.CallOption) (DumpService_CreateDumpCenterWorkerClient, error) {
	stream, err := c.cc.NewStream(ctx, &DumpService_ServiceDesc.Streams[19], "/simplebank.DumpService/CreateDumpCenterWorker", opts...)
	if err != nil {
		return nil, err
	}
	x := &dumpServiceCreateDumpCenterWorkerClient{stream}
	return x, nil
}

type DumpService_CreateDumpCenterWorkerClient interface {
	Send(*CreateDumpCenterWorkerRequest) error
	Recv() (*CreateDumpCenterWorkerResponse, error)
	grpc.ClientStream
}

type dumpServiceCreateDumpCenterWorkerClient struct {
	grpc.ClientStream
}

func (x *dumpServiceCreateDumpCenterWorkerClient) Send(m *CreateDumpCenterWorkerRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *dumpServiceCreateDumpCenterWorkerClient) Recv() (*CreateDumpCenterWorkerResponse, error) {
	m := new(CreateDumpCenterWorkerResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *dumpServiceClient) CreateDumpWriteoff(ctx context.Context, opts ...grpc.CallOption) (DumpService_CreateDumpWriteoffClient, error) {
	stream, err := c.cc.NewStream(ctx, &DumpService_ServiceDesc.Streams[20], "/simplebank.DumpService/CreateDumpWriteoff", opts...)
	if err != nil {
		return nil, err
	}
	x := &dumpServiceCreateDumpWriteoffClient{stream}
	return x, nil
}

type DumpService_CreateDumpWriteoffClient interface {
	Send(*CreateDumpWriteoffRequest) error
	Recv() (*CreateDumpWriteoffResponse, error)
	grpc.ClientStream
}

type dumpServiceCreateDumpWriteoffClient struct {
	grpc.ClientStream
}

func (x *dumpServiceCreateDumpWriteoffClient) Send(m *CreateDumpWriteoffRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *dumpServiceCreateDumpWriteoffClient) Recv() (*CreateDumpWriteoffResponse, error) {
	m := new(CreateDumpWriteoffResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *dumpServiceClient) CreateDumpAccounts(ctx context.Context, opts ...grpc.CallOption) (DumpService_CreateDumpAccountsClient, error) {
	stream, err := c.cc.NewStream(ctx, &DumpService_ServiceDesc.Streams[21], "/simplebank.DumpService/CreateDumpAccounts", opts...)
	if err != nil {
		return nil, err
	}
	x := &dumpServiceCreateDumpAccountsClient{stream}
	return x, nil
}

type DumpService_CreateDumpAccountsClient interface {
	Send(*CreateDumpAccountsRequest) error
	Recv() (*CreateDumpAccountsResponse, error)
	grpc.ClientStream
}

type dumpServiceCreateDumpAccountsClient struct {
	grpc.ClientStream
}

func (x *dumpServiceCreateDumpAccountsClient) Send(m *CreateDumpAccountsRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *dumpServiceCreateDumpAccountsClient) Recv() (*CreateDumpAccountsResponse, error) {
	m := new(CreateDumpAccountsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *dumpServiceClient) CreateDumpJnlDetails(ctx context.Context, opts ...grpc.CallOption) (DumpService_CreateDumpJnlDetailsClient, error) {
	stream, err := c.cc.NewStream(ctx, &DumpService_ServiceDesc.Streams[22], "/simplebank.DumpService/CreateDumpJnlDetails", opts...)
	if err != nil {
		return nil, err
	}
	x := &dumpServiceCreateDumpJnlDetailsClient{stream}
	return x, nil
}

type DumpService_CreateDumpJnlDetailsClient interface {
	Send(*CreateDumpJnlDetailsRequest) error
	Recv() (*CreateDumpJnlDetailsResponse, error)
	grpc.ClientStream
}

type dumpServiceCreateDumpJnlDetailsClient struct {
	grpc.ClientStream
}

func (x *dumpServiceCreateDumpJnlDetailsClient) Send(m *CreateDumpJnlDetailsRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *dumpServiceCreateDumpJnlDetailsClient) Recv() (*CreateDumpJnlDetailsResponse, error) {
	m := new(CreateDumpJnlDetailsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *dumpServiceClient) CreateDumpJnlHeaders(ctx context.Context, opts ...grpc.CallOption) (DumpService_CreateDumpJnlHeadersClient, error) {
	stream, err := c.cc.NewStream(ctx, &DumpService_ServiceDesc.Streams[23], "/simplebank.DumpService/CreateDumpJnlHeaders", opts...)
	if err != nil {
		return nil, err
	}
	x := &dumpServiceCreateDumpJnlHeadersClient{stream}
	return x, nil
}

type DumpService_CreateDumpJnlHeadersClient interface {
	Send(*CreateDumpJnlHeadersRequest) error
	Recv() (*CreateDumpJnlHeadersResponse, error)
	grpc.ClientStream
}

type dumpServiceCreateDumpJnlHeadersClient struct {
	grpc.ClientStream
}

func (x *dumpServiceCreateDumpJnlHeadersClient) Send(m *CreateDumpJnlHeadersRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *dumpServiceCreateDumpJnlHeadersClient) Recv() (*CreateDumpJnlHeadersResponse, error) {
	m := new(CreateDumpJnlHeadersResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *dumpServiceClient) CreateDumpLedgerDetails(ctx context.Context, opts ...grpc.CallOption) (DumpService_CreateDumpLedgerDetailsClient, error) {
	stream, err := c.cc.NewStream(ctx, &DumpService_ServiceDesc.Streams[24], "/simplebank.DumpService/CreateDumpLedgerDetails", opts...)
	if err != nil {
		return nil, err
	}
	x := &dumpServiceCreateDumpLedgerDetailsClient{stream}
	return x, nil
}

type DumpService_CreateDumpLedgerDetailsClient interface {
	Send(*CreateDumpLedgerDetailsRequest) error
	Recv() (*CreateDumpLedgerDetailsResponse, error)
	grpc.ClientStream
}

type dumpServiceCreateDumpLedgerDetailsClient struct {
	grpc.ClientStream
}

func (x *dumpServiceCreateDumpLedgerDetailsClient) Send(m *CreateDumpLedgerDetailsRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *dumpServiceCreateDumpLedgerDetailsClient) Recv() (*CreateDumpLedgerDetailsResponse, error) {
	m := new(CreateDumpLedgerDetailsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *dumpServiceClient) CreateDumpUsersList(ctx context.Context, opts ...grpc.CallOption) (DumpService_CreateDumpUsersListClient, error) {
	stream, err := c.cc.NewStream(ctx, &DumpService_ServiceDesc.Streams[25], "/simplebank.DumpService/CreateDumpUsersList", opts...)
	if err != nil {
		return nil, err
	}
	x := &dumpServiceCreateDumpUsersListClient{stream}
	return x, nil
}

type DumpService_CreateDumpUsersListClient interface {
	Send(*CreateDumpUsersListRequest) error
	Recv() (*CreateDumpUsersListResponse, error)
	grpc.ClientStream
}

type dumpServiceCreateDumpUsersListClient struct {
	grpc.ClientStream
}

func (x *dumpServiceCreateDumpUsersListClient) Send(m *CreateDumpUsersListRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *dumpServiceCreateDumpUsersListClient) Recv() (*CreateDumpUsersListResponse, error) {
	m := new(CreateDumpUsersListResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *dumpServiceClient) CreateDumpMultiplePaymentReceipt(ctx context.Context, opts ...grpc.CallOption) (DumpService_CreateDumpMultiplePaymentReceiptClient, error) {
	stream, err := c.cc.NewStream(ctx, &DumpService_ServiceDesc.Streams[26], "/simplebank.DumpService/CreateDumpMultiplePaymentReceipt", opts...)
	if err != nil {
		return nil, err
	}
	x := &dumpServiceCreateDumpMultiplePaymentReceiptClient{stream}
	return x, nil
}

type DumpService_CreateDumpMultiplePaymentReceiptClient interface {
	Send(*CreateDumpMultiplePaymentReceiptRequest) error
	Recv() (*CreateDumpMultiplePaymentReceiptResponse, error)
	grpc.ClientStream
}

type dumpServiceCreateDumpMultiplePaymentReceiptClient struct {
	grpc.ClientStream
}

func (x *dumpServiceCreateDumpMultiplePaymentReceiptClient) Send(m *CreateDumpMultiplePaymentReceiptRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *dumpServiceCreateDumpMultiplePaymentReceiptClient) Recv() (*CreateDumpMultiplePaymentReceiptResponse, error) {
	m := new(CreateDumpMultiplePaymentReceiptResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *dumpServiceClient) CreateDumpInActiveCID(ctx context.Context, opts ...grpc.CallOption) (DumpService_CreateDumpInActiveCIDClient, error) {
	stream, err := c.cc.NewStream(ctx, &DumpService_ServiceDesc.Streams[27], "/simplebank.DumpService/CreateDumpInActiveCID", opts...)
	if err != nil {
		return nil, err
	}
	x := &dumpServiceCreateDumpInActiveCIDClient{stream}
	return x, nil
}

type DumpService_CreateDumpInActiveCIDClient interface {
	Send(*CreateDumpInActiveCIDRequest) error
	Recv() (*CreateDumpInActiveCIDResponse, error)
	grpc.ClientStream
}

type dumpServiceCreateDumpInActiveCIDClient struct {
	grpc.ClientStream
}

func (x *dumpServiceCreateDumpInActiveCIDClient) Send(m *CreateDumpInActiveCIDRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *dumpServiceCreateDumpInActiveCIDClient) Recv() (*CreateDumpInActiveCIDResponse, error) {
	m := new(CreateDumpInActiveCIDResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *dumpServiceClient) CreateDumpLnBeneficiary(ctx context.Context, opts ...grpc.CallOption) (DumpService_CreateDumpLnBeneficiaryClient, error) {
	stream, err := c.cc.NewStream(ctx, &DumpService_ServiceDesc.Streams[28], "/simplebank.DumpService/CreateDumpLnBeneficiary", opts...)
	if err != nil {
		return nil, err
	}
	x := &dumpServiceCreateDumpLnBeneficiaryClient{stream}
	return x, nil
}

type DumpService_CreateDumpLnBeneficiaryClient interface {
	Send(*CreateDumpLnBeneficiaryRequest) error
	Recv() (*CreateDumpLnBeneficiaryResponse, error)
	grpc.ClientStream
}

type dumpServiceCreateDumpLnBeneficiaryClient struct {
	grpc.ClientStream
}

func (x *dumpServiceCreateDumpLnBeneficiaryClient) Send(m *CreateDumpLnBeneficiaryRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *dumpServiceCreateDumpLnBeneficiaryClient) Recv() (*CreateDumpLnBeneficiaryResponse, error) {
	m := new(CreateDumpLnBeneficiaryResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *dumpServiceClient) CreateDumpReactivateWriteoff(ctx context.Context, opts ...grpc.CallOption) (DumpService_CreateDumpReactivateWriteoffClient, error) {
	stream, err := c.cc.NewStream(ctx, &DumpService_ServiceDesc.Streams[29], "/simplebank.DumpService/CreateDumpReactivateWriteoff", opts...)
	if err != nil {
		return nil, err
	}
	x := &dumpServiceCreateDumpReactivateWriteoffClient{stream}
	return x, nil
}

type DumpService_CreateDumpReactivateWriteoffClient interface {
	Send(*CreateDumpReactivateWriteoffRequest) error
	Recv() (*CreateDumpReactivateWriteoffResponse, error)
	grpc.ClientStream
}

type dumpServiceCreateDumpReactivateWriteoffClient struct {
	grpc.ClientStream
}

func (x *dumpServiceCreateDumpReactivateWriteoffClient) Send(m *CreateDumpReactivateWriteoffRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *dumpServiceCreateDumpReactivateWriteoffClient) Recv() (*CreateDumpReactivateWriteoffResponse, error) {
	m := new(CreateDumpReactivateWriteoffResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *dumpServiceClient) CreateDumpColSht(ctx context.Context, opts ...grpc.CallOption) (DumpService_CreateDumpColShtClient, error) {
	stream, err := c.cc.NewStream(ctx, &DumpService_ServiceDesc.Streams[30], "/simplebank.DumpService/CreateDumpColSht", opts...)
	if err != nil {
		return nil, err
	}
	x := &dumpServiceCreateDumpColShtClient{stream}
	return x, nil
}

type DumpService_CreateDumpColShtClient interface {
	Send(*CreateDumpColShtRequest) error
	Recv() (*CreateDumpColShtResponse, error)
	grpc.ClientStream
}

type dumpServiceCreateDumpColShtClient struct {
	grpc.ClientStream
}

func (x *dumpServiceCreateDumpColShtClient) Send(m *CreateDumpColShtRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *dumpServiceCreateDumpColShtClient) Recv() (*CreateDumpColShtResponse, error) {
	m := new(CreateDumpColShtResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *dumpServiceClient) GetDumpColSht(ctx context.Context, opts ...grpc.CallOption) (DumpService_GetDumpColShtClient, error) {
	stream, err := c.cc.NewStream(ctx, &DumpService_ServiceDesc.Streams[31], "/simplebank.DumpService/GetDumpColSht", opts...)
	if err != nil {
		return nil, err
	}
	x := &dumpServiceGetDumpColShtClient{stream}
	return x, nil
}

type DumpService_GetDumpColShtClient interface {
	Send(*CreateDumpColShtRequest) error
	Recv() (*CreateDumpColShtResponse, error)
	grpc.ClientStream
}

type dumpServiceGetDumpColShtClient struct {
	grpc.ClientStream
}

func (x *dumpServiceGetDumpColShtClient) Send(m *CreateDumpColShtRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *dumpServiceGetDumpColShtClient) Recv() (*CreateDumpColShtResponse, error) {
	m := new(CreateDumpColShtResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// DumpServiceServer is the server API for DumpService service.
// All implementations must embed UnimplementedDumpServiceServer
// for forward compatibility
type DumpServiceServer interface {
	GetModifiedTable(*GetModifiedTableRequest, DumpService_GetModifiedTableServer) error
	GetDumpBranchList(context.Context, *GetDumpBranchListRequest) (*DumpBranchList, error)
	ListDumpBranchList(*NoParam, DumpService_ListDumpBranchListServer) error
	CreateDumpBranchList(context.Context, *CreateDumpBranchListRequest) (*CreateDumpBranchListResponse, error)
	UpdateDumpBranchList(context.Context, *UpdateDumpBranchListRequest) (*UpdateDumpBranchListResponse, error)
	CreateDumpArea(DumpService_CreateDumpAreaServer) error
	CreateDumpUnit(DumpService_CreateDumpUnitServer) error
	CreateDumpCenter(DumpService_CreateDumpCenterServer) error
	CreateDumpCustomer(DumpService_CreateDumpCustomerServer) error
	CreateDumpAddresses(DumpService_CreateDumpAddressesServer) error
	CreateDumpLnMaster(DumpService_CreateDumpLnMasterServer) error
	CreateDumpSaMaster(DumpService_CreateDumpSaMasterServer) error
	CreateDumpTrnMaster(DumpService_CreateDumpTrnMasterServer) error
	CreateDumpSaTrnMaster(DumpService_CreateDumpSaTrnMasterServer) error
	CreateDumpLoanInst(DumpService_CreateDumpLoanInstServer) error
	CreateDumpLnChrgData(DumpService_CreateDumpLnChrgDataServer) error
	CreateDumpCustAddInfoGroup(DumpService_CreateDumpCustAddInfoGroupServer) error
	CreateDumpCustAddInfoList(DumpService_CreateDumpCustAddInfoListServer) error
	CreateDumpCustAddInfoGroupNeed(DumpService_CreateDumpCustAddInfoGroupNeedServer) error
	CreateDumpCustAddInfo(DumpService_CreateDumpCustAddInfoServer) error
	CreateDumpMutualFund(DumpService_CreateDumpMutualFundServer) error
	CreateDumpReferencesDetails(DumpService_CreateDumpReferencesDetailsServer) error
	CreateDumpCenterWorker(DumpService_CreateDumpCenterWorkerServer) error
	CreateDumpWriteoff(DumpService_CreateDumpWriteoffServer) error
	CreateDumpAccounts(DumpService_CreateDumpAccountsServer) error
	CreateDumpJnlDetails(DumpService_CreateDumpJnlDetailsServer) error
	CreateDumpJnlHeaders(DumpService_CreateDumpJnlHeadersServer) error
	CreateDumpLedgerDetails(DumpService_CreateDumpLedgerDetailsServer) error
	CreateDumpUsersList(DumpService_CreateDumpUsersListServer) error
	CreateDumpMultiplePaymentReceipt(DumpService_CreateDumpMultiplePaymentReceiptServer) error
	CreateDumpInActiveCID(DumpService_CreateDumpInActiveCIDServer) error
	CreateDumpLnBeneficiary(DumpService_CreateDumpLnBeneficiaryServer) error
	CreateDumpReactivateWriteoff(DumpService_CreateDumpReactivateWriteoffServer) error
	CreateDumpColSht(DumpService_CreateDumpColShtServer) error
	GetDumpColSht(DumpService_GetDumpColShtServer) error
	mustEmbedUnimplementedDumpServiceServer()
}

// UnimplementedDumpServiceServer must be embedded to have forward compatible implementations.
type UnimplementedDumpServiceServer struct {
}

func (UnimplementedDumpServiceServer) GetModifiedTable(*GetModifiedTableRequest, DumpService_GetModifiedTableServer) error {
	return status.Errorf(codes.Unimplemented, "method GetModifiedTable not implemented")
}
func (UnimplementedDumpServiceServer) GetDumpBranchList(context.Context, *GetDumpBranchListRequest) (*DumpBranchList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDumpBranchList not implemented")
}
func (UnimplementedDumpServiceServer) ListDumpBranchList(*NoParam, DumpService_ListDumpBranchListServer) error {
	return status.Errorf(codes.Unimplemented, "method ListDumpBranchList not implemented")
}
func (UnimplementedDumpServiceServer) CreateDumpBranchList(context.Context, *CreateDumpBranchListRequest) (*CreateDumpBranchListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateDumpBranchList not implemented")
}
func (UnimplementedDumpServiceServer) UpdateDumpBranchList(context.Context, *UpdateDumpBranchListRequest) (*UpdateDumpBranchListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateDumpBranchList not implemented")
}
func (UnimplementedDumpServiceServer) CreateDumpArea(DumpService_CreateDumpAreaServer) error {
	return status.Errorf(codes.Unimplemented, "method CreateDumpArea not implemented")
}
func (UnimplementedDumpServiceServer) CreateDumpUnit(DumpService_CreateDumpUnitServer) error {
	return status.Errorf(codes.Unimplemented, "method CreateDumpUnit not implemented")
}
func (UnimplementedDumpServiceServer) CreateDumpCenter(DumpService_CreateDumpCenterServer) error {
	return status.Errorf(codes.Unimplemented, "method CreateDumpCenter not implemented")
}
func (UnimplementedDumpServiceServer) CreateDumpCustomer(DumpService_CreateDumpCustomerServer) error {
	return status.Errorf(codes.Unimplemented, "method CreateDumpCustomer not implemented")
}
func (UnimplementedDumpServiceServer) CreateDumpAddresses(DumpService_CreateDumpAddressesServer) error {
	return status.Errorf(codes.Unimplemented, "method CreateDumpAddresses not implemented")
}
func (UnimplementedDumpServiceServer) CreateDumpLnMaster(DumpService_CreateDumpLnMasterServer) error {
	return status.Errorf(codes.Unimplemented, "method CreateDumpLnMaster not implemented")
}
func (UnimplementedDumpServiceServer) CreateDumpSaMaster(DumpService_CreateDumpSaMasterServer) error {
	return status.Errorf(codes.Unimplemented, "method CreateDumpSaMaster not implemented")
}
func (UnimplementedDumpServiceServer) CreateDumpTrnMaster(DumpService_CreateDumpTrnMasterServer) error {
	return status.Errorf(codes.Unimplemented, "method CreateDumpTrnMaster not implemented")
}
func (UnimplementedDumpServiceServer) CreateDumpSaTrnMaster(DumpService_CreateDumpSaTrnMasterServer) error {
	return status.Errorf(codes.Unimplemented, "method CreateDumpSaTrnMaster not implemented")
}
func (UnimplementedDumpServiceServer) CreateDumpLoanInst(DumpService_CreateDumpLoanInstServer) error {
	return status.Errorf(codes.Unimplemented, "method CreateDumpLoanInst not implemented")
}
func (UnimplementedDumpServiceServer) CreateDumpLnChrgData(DumpService_CreateDumpLnChrgDataServer) error {
	return status.Errorf(codes.Unimplemented, "method CreateDumpLnChrgData not implemented")
}
func (UnimplementedDumpServiceServer) CreateDumpCustAddInfoGroup(DumpService_CreateDumpCustAddInfoGroupServer) error {
	return status.Errorf(codes.Unimplemented, "method CreateDumpCustAddInfoGroup not implemented")
}
func (UnimplementedDumpServiceServer) CreateDumpCustAddInfoList(DumpService_CreateDumpCustAddInfoListServer) error {
	return status.Errorf(codes.Unimplemented, "method CreateDumpCustAddInfoList not implemented")
}
func (UnimplementedDumpServiceServer) CreateDumpCustAddInfoGroupNeed(DumpService_CreateDumpCustAddInfoGroupNeedServer) error {
	return status.Errorf(codes.Unimplemented, "method CreateDumpCustAddInfoGroupNeed not implemented")
}
func (UnimplementedDumpServiceServer) CreateDumpCustAddInfo(DumpService_CreateDumpCustAddInfoServer) error {
	return status.Errorf(codes.Unimplemented, "method CreateDumpCustAddInfo not implemented")
}
func (UnimplementedDumpServiceServer) CreateDumpMutualFund(DumpService_CreateDumpMutualFundServer) error {
	return status.Errorf(codes.Unimplemented, "method CreateDumpMutualFund not implemented")
}
func (UnimplementedDumpServiceServer) CreateDumpReferencesDetails(DumpService_CreateDumpReferencesDetailsServer) error {
	return status.Errorf(codes.Unimplemented, "method CreateDumpReferencesDetails not implemented")
}
func (UnimplementedDumpServiceServer) CreateDumpCenterWorker(DumpService_CreateDumpCenterWorkerServer) error {
	return status.Errorf(codes.Unimplemented, "method CreateDumpCenterWorker not implemented")
}
func (UnimplementedDumpServiceServer) CreateDumpWriteoff(DumpService_CreateDumpWriteoffServer) error {
	return status.Errorf(codes.Unimplemented, "method CreateDumpWriteoff not implemented")
}
func (UnimplementedDumpServiceServer) CreateDumpAccounts(DumpService_CreateDumpAccountsServer) error {
	return status.Errorf(codes.Unimplemented, "method CreateDumpAccounts not implemented")
}
func (UnimplementedDumpServiceServer) CreateDumpJnlDetails(DumpService_CreateDumpJnlDetailsServer) error {
	return status.Errorf(codes.Unimplemented, "method CreateDumpJnlDetails not implemented")
}
func (UnimplementedDumpServiceServer) CreateDumpJnlHeaders(DumpService_CreateDumpJnlHeadersServer) error {
	return status.Errorf(codes.Unimplemented, "method CreateDumpJnlHeaders not implemented")
}
func (UnimplementedDumpServiceServer) CreateDumpLedgerDetails(DumpService_CreateDumpLedgerDetailsServer) error {
	return status.Errorf(codes.Unimplemented, "method CreateDumpLedgerDetails not implemented")
}
func (UnimplementedDumpServiceServer) CreateDumpUsersList(DumpService_CreateDumpUsersListServer) error {
	return status.Errorf(codes.Unimplemented, "method CreateDumpUsersList not implemented")
}
func (UnimplementedDumpServiceServer) CreateDumpMultiplePaymentReceipt(DumpService_CreateDumpMultiplePaymentReceiptServer) error {
	return status.Errorf(codes.Unimplemented, "method CreateDumpMultiplePaymentReceipt not implemented")
}
func (UnimplementedDumpServiceServer) CreateDumpInActiveCID(DumpService_CreateDumpInActiveCIDServer) error {
	return status.Errorf(codes.Unimplemented, "method CreateDumpInActiveCID not implemented")
}
func (UnimplementedDumpServiceServer) CreateDumpLnBeneficiary(DumpService_CreateDumpLnBeneficiaryServer) error {
	return status.Errorf(codes.Unimplemented, "method CreateDumpLnBeneficiary not implemented")
}
func (UnimplementedDumpServiceServer) CreateDumpReactivateWriteoff(DumpService_CreateDumpReactivateWriteoffServer) error {
	return status.Errorf(codes.Unimplemented, "method CreateDumpReactivateWriteoff not implemented")
}
func (UnimplementedDumpServiceServer) CreateDumpColSht(DumpService_CreateDumpColShtServer) error {
	return status.Errorf(codes.Unimplemented, "method CreateDumpColSht not implemented")
}
func (UnimplementedDumpServiceServer) GetDumpColSht(DumpService_GetDumpColShtServer) error {
	return status.Errorf(codes.Unimplemented, "method GetDumpColSht not implemented")
}
func (UnimplementedDumpServiceServer) mustEmbedUnimplementedDumpServiceServer() {}

// UnsafeDumpServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DumpServiceServer will
// result in compilation errors.
type UnsafeDumpServiceServer interface {
	mustEmbedUnimplementedDumpServiceServer()
}

func RegisterDumpServiceServer(s grpc.ServiceRegistrar, srv DumpServiceServer) {
	s.RegisterService(&DumpService_ServiceDesc, srv)
}

func _DumpService_GetModifiedTable_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetModifiedTableRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DumpServiceServer).GetModifiedTable(m, &dumpServiceGetModifiedTableServer{stream})
}

type DumpService_GetModifiedTableServer interface {
	Send(*DumpModifiedTable) error
	grpc.ServerStream
}

type dumpServiceGetModifiedTableServer struct {
	grpc.ServerStream
}

func (x *dumpServiceGetModifiedTableServer) Send(m *DumpModifiedTable) error {
	return x.ServerStream.SendMsg(m)
}

func _DumpService_GetDumpBranchList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDumpBranchListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DumpServiceServer).GetDumpBranchList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/simplebank.DumpService/GetDumpBranchList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DumpServiceServer).GetDumpBranchList(ctx, req.(*GetDumpBranchListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DumpService_ListDumpBranchList_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(NoParam)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DumpServiceServer).ListDumpBranchList(m, &dumpServiceListDumpBranchListServer{stream})
}

type DumpService_ListDumpBranchListServer interface {
	Send(*DumpBranchList) error
	grpc.ServerStream
}

type dumpServiceListDumpBranchListServer struct {
	grpc.ServerStream
}

func (x *dumpServiceListDumpBranchListServer) Send(m *DumpBranchList) error {
	return x.ServerStream.SendMsg(m)
}

func _DumpService_CreateDumpBranchList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateDumpBranchListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DumpServiceServer).CreateDumpBranchList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/simplebank.DumpService/CreateDumpBranchList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DumpServiceServer).CreateDumpBranchList(ctx, req.(*CreateDumpBranchListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DumpService_UpdateDumpBranchList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateDumpBranchListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DumpServiceServer).UpdateDumpBranchList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/simplebank.DumpService/UpdateDumpBranchList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DumpServiceServer).UpdateDumpBranchList(ctx, req.(*UpdateDumpBranchListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DumpService_CreateDumpArea_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DumpServiceServer).CreateDumpArea(&dumpServiceCreateDumpAreaServer{stream})
}

type DumpService_CreateDumpAreaServer interface {
	Send(*CreateDumpAreaResponse) error
	Recv() (*CreateDumpAreaRequest, error)
	grpc.ServerStream
}

type dumpServiceCreateDumpAreaServer struct {
	grpc.ServerStream
}

func (x *dumpServiceCreateDumpAreaServer) Send(m *CreateDumpAreaResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *dumpServiceCreateDumpAreaServer) Recv() (*CreateDumpAreaRequest, error) {
	m := new(CreateDumpAreaRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _DumpService_CreateDumpUnit_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DumpServiceServer).CreateDumpUnit(&dumpServiceCreateDumpUnitServer{stream})
}

type DumpService_CreateDumpUnitServer interface {
	Send(*CreateDumpUnitResponse) error
	Recv() (*CreateDumpUnitRequest, error)
	grpc.ServerStream
}

type dumpServiceCreateDumpUnitServer struct {
	grpc.ServerStream
}

func (x *dumpServiceCreateDumpUnitServer) Send(m *CreateDumpUnitResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *dumpServiceCreateDumpUnitServer) Recv() (*CreateDumpUnitRequest, error) {
	m := new(CreateDumpUnitRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _DumpService_CreateDumpCenter_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DumpServiceServer).CreateDumpCenter(&dumpServiceCreateDumpCenterServer{stream})
}

type DumpService_CreateDumpCenterServer interface {
	Send(*CreateDumpCenterResponse) error
	Recv() (*CreateDumpCenterRequest, error)
	grpc.ServerStream
}

type dumpServiceCreateDumpCenterServer struct {
	grpc.ServerStream
}

func (x *dumpServiceCreateDumpCenterServer) Send(m *CreateDumpCenterResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *dumpServiceCreateDumpCenterServer) Recv() (*CreateDumpCenterRequest, error) {
	m := new(CreateDumpCenterRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _DumpService_CreateDumpCustomer_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DumpServiceServer).CreateDumpCustomer(&dumpServiceCreateDumpCustomerServer{stream})
}

type DumpService_CreateDumpCustomerServer interface {
	Send(*CreateDumpCustomerResponse) error
	Recv() (*CreateDumpCustomerRequest, error)
	grpc.ServerStream
}

type dumpServiceCreateDumpCustomerServer struct {
	grpc.ServerStream
}

func (x *dumpServiceCreateDumpCustomerServer) Send(m *CreateDumpCustomerResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *dumpServiceCreateDumpCustomerServer) Recv() (*CreateDumpCustomerRequest, error) {
	m := new(CreateDumpCustomerRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _DumpService_CreateDumpAddresses_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DumpServiceServer).CreateDumpAddresses(&dumpServiceCreateDumpAddressesServer{stream})
}

type DumpService_CreateDumpAddressesServer interface {
	Send(*CreateDumpAddressesResponse) error
	Recv() (*CreateDumpAddressesRequest, error)
	grpc.ServerStream
}

type dumpServiceCreateDumpAddressesServer struct {
	grpc.ServerStream
}

func (x *dumpServiceCreateDumpAddressesServer) Send(m *CreateDumpAddressesResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *dumpServiceCreateDumpAddressesServer) Recv() (*CreateDumpAddressesRequest, error) {
	m := new(CreateDumpAddressesRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _DumpService_CreateDumpLnMaster_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DumpServiceServer).CreateDumpLnMaster(&dumpServiceCreateDumpLnMasterServer{stream})
}

type DumpService_CreateDumpLnMasterServer interface {
	Send(*CreateDumpLnMasterResponse) error
	Recv() (*CreateDumpLnMasterRequest, error)
	grpc.ServerStream
}

type dumpServiceCreateDumpLnMasterServer struct {
	grpc.ServerStream
}

func (x *dumpServiceCreateDumpLnMasterServer) Send(m *CreateDumpLnMasterResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *dumpServiceCreateDumpLnMasterServer) Recv() (*CreateDumpLnMasterRequest, error) {
	m := new(CreateDumpLnMasterRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _DumpService_CreateDumpSaMaster_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DumpServiceServer).CreateDumpSaMaster(&dumpServiceCreateDumpSaMasterServer{stream})
}

type DumpService_CreateDumpSaMasterServer interface {
	Send(*CreateDumpSaMasterResponse) error
	Recv() (*CreateDumpSaMasterRequest, error)
	grpc.ServerStream
}

type dumpServiceCreateDumpSaMasterServer struct {
	grpc.ServerStream
}

func (x *dumpServiceCreateDumpSaMasterServer) Send(m *CreateDumpSaMasterResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *dumpServiceCreateDumpSaMasterServer) Recv() (*CreateDumpSaMasterRequest, error) {
	m := new(CreateDumpSaMasterRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _DumpService_CreateDumpTrnMaster_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DumpServiceServer).CreateDumpTrnMaster(&dumpServiceCreateDumpTrnMasterServer{stream})
}

type DumpService_CreateDumpTrnMasterServer interface {
	Send(*CreateDumpTrnMasterResponse) error
	Recv() (*CreateDumpTrnMasterRequest, error)
	grpc.ServerStream
}

type dumpServiceCreateDumpTrnMasterServer struct {
	grpc.ServerStream
}

func (x *dumpServiceCreateDumpTrnMasterServer) Send(m *CreateDumpTrnMasterResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *dumpServiceCreateDumpTrnMasterServer) Recv() (*CreateDumpTrnMasterRequest, error) {
	m := new(CreateDumpTrnMasterRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _DumpService_CreateDumpSaTrnMaster_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DumpServiceServer).CreateDumpSaTrnMaster(&dumpServiceCreateDumpSaTrnMasterServer{stream})
}

type DumpService_CreateDumpSaTrnMasterServer interface {
	Send(*CreateDumpSaTrnMasterResponse) error
	Recv() (*CreateDumpSaTrnMasterRequest, error)
	grpc.ServerStream
}

type dumpServiceCreateDumpSaTrnMasterServer struct {
	grpc.ServerStream
}

func (x *dumpServiceCreateDumpSaTrnMasterServer) Send(m *CreateDumpSaTrnMasterResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *dumpServiceCreateDumpSaTrnMasterServer) Recv() (*CreateDumpSaTrnMasterRequest, error) {
	m := new(CreateDumpSaTrnMasterRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _DumpService_CreateDumpLoanInst_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DumpServiceServer).CreateDumpLoanInst(&dumpServiceCreateDumpLoanInstServer{stream})
}

type DumpService_CreateDumpLoanInstServer interface {
	Send(*CreateDumpLoanInstResponse) error
	Recv() (*CreateDumpLoanInstRequest, error)
	grpc.ServerStream
}

type dumpServiceCreateDumpLoanInstServer struct {
	grpc.ServerStream
}

func (x *dumpServiceCreateDumpLoanInstServer) Send(m *CreateDumpLoanInstResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *dumpServiceCreateDumpLoanInstServer) Recv() (*CreateDumpLoanInstRequest, error) {
	m := new(CreateDumpLoanInstRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _DumpService_CreateDumpLnChrgData_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DumpServiceServer).CreateDumpLnChrgData(&dumpServiceCreateDumpLnChrgDataServer{stream})
}

type DumpService_CreateDumpLnChrgDataServer interface {
	Send(*CreateDumpLnChrgDataResponse) error
	Recv() (*CreateDumpLnChrgDataRequest, error)
	grpc.ServerStream
}

type dumpServiceCreateDumpLnChrgDataServer struct {
	grpc.ServerStream
}

func (x *dumpServiceCreateDumpLnChrgDataServer) Send(m *CreateDumpLnChrgDataResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *dumpServiceCreateDumpLnChrgDataServer) Recv() (*CreateDumpLnChrgDataRequest, error) {
	m := new(CreateDumpLnChrgDataRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _DumpService_CreateDumpCustAddInfoGroup_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DumpServiceServer).CreateDumpCustAddInfoGroup(&dumpServiceCreateDumpCustAddInfoGroupServer{stream})
}

type DumpService_CreateDumpCustAddInfoGroupServer interface {
	Send(*CreateDumpCustAddInfoGroupResponse) error
	Recv() (*CreateDumpCustAddInfoGroupRequest, error)
	grpc.ServerStream
}

type dumpServiceCreateDumpCustAddInfoGroupServer struct {
	grpc.ServerStream
}

func (x *dumpServiceCreateDumpCustAddInfoGroupServer) Send(m *CreateDumpCustAddInfoGroupResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *dumpServiceCreateDumpCustAddInfoGroupServer) Recv() (*CreateDumpCustAddInfoGroupRequest, error) {
	m := new(CreateDumpCustAddInfoGroupRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _DumpService_CreateDumpCustAddInfoList_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DumpServiceServer).CreateDumpCustAddInfoList(&dumpServiceCreateDumpCustAddInfoListServer{stream})
}

type DumpService_CreateDumpCustAddInfoListServer interface {
	Send(*CreateDumpCustAddInfoListResponse) error
	Recv() (*CreateDumpCustAddInfoListRequest, error)
	grpc.ServerStream
}

type dumpServiceCreateDumpCustAddInfoListServer struct {
	grpc.ServerStream
}

func (x *dumpServiceCreateDumpCustAddInfoListServer) Send(m *CreateDumpCustAddInfoListResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *dumpServiceCreateDumpCustAddInfoListServer) Recv() (*CreateDumpCustAddInfoListRequest, error) {
	m := new(CreateDumpCustAddInfoListRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _DumpService_CreateDumpCustAddInfoGroupNeed_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DumpServiceServer).CreateDumpCustAddInfoGroupNeed(&dumpServiceCreateDumpCustAddInfoGroupNeedServer{stream})
}

type DumpService_CreateDumpCustAddInfoGroupNeedServer interface {
	Send(*CreateDumpCustAddInfoGroupNeedResponse) error
	Recv() (*CreateDumpCustAddInfoGroupNeedRequest, error)
	grpc.ServerStream
}

type dumpServiceCreateDumpCustAddInfoGroupNeedServer struct {
	grpc.ServerStream
}

func (x *dumpServiceCreateDumpCustAddInfoGroupNeedServer) Send(m *CreateDumpCustAddInfoGroupNeedResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *dumpServiceCreateDumpCustAddInfoGroupNeedServer) Recv() (*CreateDumpCustAddInfoGroupNeedRequest, error) {
	m := new(CreateDumpCustAddInfoGroupNeedRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _DumpService_CreateDumpCustAddInfo_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DumpServiceServer).CreateDumpCustAddInfo(&dumpServiceCreateDumpCustAddInfoServer{stream})
}

type DumpService_CreateDumpCustAddInfoServer interface {
	Send(*CreateDumpCustAddInfoResponse) error
	Recv() (*CreateDumpCustAddInfoRequest, error)
	grpc.ServerStream
}

type dumpServiceCreateDumpCustAddInfoServer struct {
	grpc.ServerStream
}

func (x *dumpServiceCreateDumpCustAddInfoServer) Send(m *CreateDumpCustAddInfoResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *dumpServiceCreateDumpCustAddInfoServer) Recv() (*CreateDumpCustAddInfoRequest, error) {
	m := new(CreateDumpCustAddInfoRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _DumpService_CreateDumpMutualFund_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DumpServiceServer).CreateDumpMutualFund(&dumpServiceCreateDumpMutualFundServer{stream})
}

type DumpService_CreateDumpMutualFundServer interface {
	Send(*CreateDumpMutualFundResponse) error
	Recv() (*CreateDumpMutualFundRequest, error)
	grpc.ServerStream
}

type dumpServiceCreateDumpMutualFundServer struct {
	grpc.ServerStream
}

func (x *dumpServiceCreateDumpMutualFundServer) Send(m *CreateDumpMutualFundResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *dumpServiceCreateDumpMutualFundServer) Recv() (*CreateDumpMutualFundRequest, error) {
	m := new(CreateDumpMutualFundRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _DumpService_CreateDumpReferencesDetails_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DumpServiceServer).CreateDumpReferencesDetails(&dumpServiceCreateDumpReferencesDetailsServer{stream})
}

type DumpService_CreateDumpReferencesDetailsServer interface {
	Send(*CreateDumpReferencesDetailsResponse) error
	Recv() (*CreateDumpReferencesDetailsRequest, error)
	grpc.ServerStream
}

type dumpServiceCreateDumpReferencesDetailsServer struct {
	grpc.ServerStream
}

func (x *dumpServiceCreateDumpReferencesDetailsServer) Send(m *CreateDumpReferencesDetailsResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *dumpServiceCreateDumpReferencesDetailsServer) Recv() (*CreateDumpReferencesDetailsRequest, error) {
	m := new(CreateDumpReferencesDetailsRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _DumpService_CreateDumpCenterWorker_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DumpServiceServer).CreateDumpCenterWorker(&dumpServiceCreateDumpCenterWorkerServer{stream})
}

type DumpService_CreateDumpCenterWorkerServer interface {
	Send(*CreateDumpCenterWorkerResponse) error
	Recv() (*CreateDumpCenterWorkerRequest, error)
	grpc.ServerStream
}

type dumpServiceCreateDumpCenterWorkerServer struct {
	grpc.ServerStream
}

func (x *dumpServiceCreateDumpCenterWorkerServer) Send(m *CreateDumpCenterWorkerResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *dumpServiceCreateDumpCenterWorkerServer) Recv() (*CreateDumpCenterWorkerRequest, error) {
	m := new(CreateDumpCenterWorkerRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _DumpService_CreateDumpWriteoff_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DumpServiceServer).CreateDumpWriteoff(&dumpServiceCreateDumpWriteoffServer{stream})
}

type DumpService_CreateDumpWriteoffServer interface {
	Send(*CreateDumpWriteoffResponse) error
	Recv() (*CreateDumpWriteoffRequest, error)
	grpc.ServerStream
}

type dumpServiceCreateDumpWriteoffServer struct {
	grpc.ServerStream
}

func (x *dumpServiceCreateDumpWriteoffServer) Send(m *CreateDumpWriteoffResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *dumpServiceCreateDumpWriteoffServer) Recv() (*CreateDumpWriteoffRequest, error) {
	m := new(CreateDumpWriteoffRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _DumpService_CreateDumpAccounts_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DumpServiceServer).CreateDumpAccounts(&dumpServiceCreateDumpAccountsServer{stream})
}

type DumpService_CreateDumpAccountsServer interface {
	Send(*CreateDumpAccountsResponse) error
	Recv() (*CreateDumpAccountsRequest, error)
	grpc.ServerStream
}

type dumpServiceCreateDumpAccountsServer struct {
	grpc.ServerStream
}

func (x *dumpServiceCreateDumpAccountsServer) Send(m *CreateDumpAccountsResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *dumpServiceCreateDumpAccountsServer) Recv() (*CreateDumpAccountsRequest, error) {
	m := new(CreateDumpAccountsRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _DumpService_CreateDumpJnlDetails_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DumpServiceServer).CreateDumpJnlDetails(&dumpServiceCreateDumpJnlDetailsServer{stream})
}

type DumpService_CreateDumpJnlDetailsServer interface {
	Send(*CreateDumpJnlDetailsResponse) error
	Recv() (*CreateDumpJnlDetailsRequest, error)
	grpc.ServerStream
}

type dumpServiceCreateDumpJnlDetailsServer struct {
	grpc.ServerStream
}

func (x *dumpServiceCreateDumpJnlDetailsServer) Send(m *CreateDumpJnlDetailsResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *dumpServiceCreateDumpJnlDetailsServer) Recv() (*CreateDumpJnlDetailsRequest, error) {
	m := new(CreateDumpJnlDetailsRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _DumpService_CreateDumpJnlHeaders_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DumpServiceServer).CreateDumpJnlHeaders(&dumpServiceCreateDumpJnlHeadersServer{stream})
}

type DumpService_CreateDumpJnlHeadersServer interface {
	Send(*CreateDumpJnlHeadersResponse) error
	Recv() (*CreateDumpJnlHeadersRequest, error)
	grpc.ServerStream
}

type dumpServiceCreateDumpJnlHeadersServer struct {
	grpc.ServerStream
}

func (x *dumpServiceCreateDumpJnlHeadersServer) Send(m *CreateDumpJnlHeadersResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *dumpServiceCreateDumpJnlHeadersServer) Recv() (*CreateDumpJnlHeadersRequest, error) {
	m := new(CreateDumpJnlHeadersRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _DumpService_CreateDumpLedgerDetails_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DumpServiceServer).CreateDumpLedgerDetails(&dumpServiceCreateDumpLedgerDetailsServer{stream})
}

type DumpService_CreateDumpLedgerDetailsServer interface {
	Send(*CreateDumpLedgerDetailsResponse) error
	Recv() (*CreateDumpLedgerDetailsRequest, error)
	grpc.ServerStream
}

type dumpServiceCreateDumpLedgerDetailsServer struct {
	grpc.ServerStream
}

func (x *dumpServiceCreateDumpLedgerDetailsServer) Send(m *CreateDumpLedgerDetailsResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *dumpServiceCreateDumpLedgerDetailsServer) Recv() (*CreateDumpLedgerDetailsRequest, error) {
	m := new(CreateDumpLedgerDetailsRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _DumpService_CreateDumpUsersList_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DumpServiceServer).CreateDumpUsersList(&dumpServiceCreateDumpUsersListServer{stream})
}

type DumpService_CreateDumpUsersListServer interface {
	Send(*CreateDumpUsersListResponse) error
	Recv() (*CreateDumpUsersListRequest, error)
	grpc.ServerStream
}

type dumpServiceCreateDumpUsersListServer struct {
	grpc.ServerStream
}

func (x *dumpServiceCreateDumpUsersListServer) Send(m *CreateDumpUsersListResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *dumpServiceCreateDumpUsersListServer) Recv() (*CreateDumpUsersListRequest, error) {
	m := new(CreateDumpUsersListRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _DumpService_CreateDumpMultiplePaymentReceipt_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DumpServiceServer).CreateDumpMultiplePaymentReceipt(&dumpServiceCreateDumpMultiplePaymentReceiptServer{stream})
}

type DumpService_CreateDumpMultiplePaymentReceiptServer interface {
	Send(*CreateDumpMultiplePaymentReceiptResponse) error
	Recv() (*CreateDumpMultiplePaymentReceiptRequest, error)
	grpc.ServerStream
}

type dumpServiceCreateDumpMultiplePaymentReceiptServer struct {
	grpc.ServerStream
}

func (x *dumpServiceCreateDumpMultiplePaymentReceiptServer) Send(m *CreateDumpMultiplePaymentReceiptResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *dumpServiceCreateDumpMultiplePaymentReceiptServer) Recv() (*CreateDumpMultiplePaymentReceiptRequest, error) {
	m := new(CreateDumpMultiplePaymentReceiptRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _DumpService_CreateDumpInActiveCID_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DumpServiceServer).CreateDumpInActiveCID(&dumpServiceCreateDumpInActiveCIDServer{stream})
}

type DumpService_CreateDumpInActiveCIDServer interface {
	Send(*CreateDumpInActiveCIDResponse) error
	Recv() (*CreateDumpInActiveCIDRequest, error)
	grpc.ServerStream
}

type dumpServiceCreateDumpInActiveCIDServer struct {
	grpc.ServerStream
}

func (x *dumpServiceCreateDumpInActiveCIDServer) Send(m *CreateDumpInActiveCIDResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *dumpServiceCreateDumpInActiveCIDServer) Recv() (*CreateDumpInActiveCIDRequest, error) {
	m := new(CreateDumpInActiveCIDRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _DumpService_CreateDumpLnBeneficiary_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DumpServiceServer).CreateDumpLnBeneficiary(&dumpServiceCreateDumpLnBeneficiaryServer{stream})
}

type DumpService_CreateDumpLnBeneficiaryServer interface {
	Send(*CreateDumpLnBeneficiaryResponse) error
	Recv() (*CreateDumpLnBeneficiaryRequest, error)
	grpc.ServerStream
}

type dumpServiceCreateDumpLnBeneficiaryServer struct {
	grpc.ServerStream
}

func (x *dumpServiceCreateDumpLnBeneficiaryServer) Send(m *CreateDumpLnBeneficiaryResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *dumpServiceCreateDumpLnBeneficiaryServer) Recv() (*CreateDumpLnBeneficiaryRequest, error) {
	m := new(CreateDumpLnBeneficiaryRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _DumpService_CreateDumpReactivateWriteoff_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DumpServiceServer).CreateDumpReactivateWriteoff(&dumpServiceCreateDumpReactivateWriteoffServer{stream})
}

type DumpService_CreateDumpReactivateWriteoffServer interface {
	Send(*CreateDumpReactivateWriteoffResponse) error
	Recv() (*CreateDumpReactivateWriteoffRequest, error)
	grpc.ServerStream
}

type dumpServiceCreateDumpReactivateWriteoffServer struct {
	grpc.ServerStream
}

func (x *dumpServiceCreateDumpReactivateWriteoffServer) Send(m *CreateDumpReactivateWriteoffResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *dumpServiceCreateDumpReactivateWriteoffServer) Recv() (*CreateDumpReactivateWriteoffRequest, error) {
	m := new(CreateDumpReactivateWriteoffRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _DumpService_CreateDumpColSht_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DumpServiceServer).CreateDumpColSht(&dumpServiceCreateDumpColShtServer{stream})
}

type DumpService_CreateDumpColShtServer interface {
	Send(*CreateDumpColShtResponse) error
	Recv() (*CreateDumpColShtRequest, error)
	grpc.ServerStream
}

type dumpServiceCreateDumpColShtServer struct {
	grpc.ServerStream
}

func (x *dumpServiceCreateDumpColShtServer) Send(m *CreateDumpColShtResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *dumpServiceCreateDumpColShtServer) Recv() (*CreateDumpColShtRequest, error) {
	m := new(CreateDumpColShtRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _DumpService_GetDumpColSht_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DumpServiceServer).GetDumpColSht(&dumpServiceGetDumpColShtServer{stream})
}

type DumpService_GetDumpColShtServer interface {
	Send(*CreateDumpColShtResponse) error
	Recv() (*CreateDumpColShtRequest, error)
	grpc.ServerStream
}

type dumpServiceGetDumpColShtServer struct {
	grpc.ServerStream
}

func (x *dumpServiceGetDumpColShtServer) Send(m *CreateDumpColShtResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *dumpServiceGetDumpColShtServer) Recv() (*CreateDumpColShtRequest, error) {
	m := new(CreateDumpColShtRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// DumpService_ServiceDesc is the grpc.ServiceDesc for DumpService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DumpService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "simplebank.DumpService",
	HandlerType: (*DumpServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetDumpBranchList",
			Handler:    _DumpService_GetDumpBranchList_Handler,
		},
		{
			MethodName: "CreateDumpBranchList",
			Handler:    _DumpService_CreateDumpBranchList_Handler,
		},
		{
			MethodName: "UpdateDumpBranchList",
			Handler:    _DumpService_UpdateDumpBranchList_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetModifiedTable",
			Handler:       _DumpService_GetModifiedTable_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ListDumpBranchList",
			Handler:       _DumpService_ListDumpBranchList_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "CreateDumpArea",
			Handler:       _DumpService_CreateDumpArea_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "CreateDumpUnit",
			Handler:       _DumpService_CreateDumpUnit_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "CreateDumpCenter",
			Handler:       _DumpService_CreateDumpCenter_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "CreateDumpCustomer",
			Handler:       _DumpService_CreateDumpCustomer_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "CreateDumpAddresses",
			Handler:       _DumpService_CreateDumpAddresses_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "CreateDumpLnMaster",
			Handler:       _DumpService_CreateDumpLnMaster_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "CreateDumpSaMaster",
			Handler:       _DumpService_CreateDumpSaMaster_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "CreateDumpTrnMaster",
			Handler:       _DumpService_CreateDumpTrnMaster_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "CreateDumpSaTrnMaster",
			Handler:       _DumpService_CreateDumpSaTrnMaster_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "CreateDumpLoanInst",
			Handler:       _DumpService_CreateDumpLoanInst_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "CreateDumpLnChrgData",
			Handler:       _DumpService_CreateDumpLnChrgData_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "CreateDumpCustAddInfoGroup",
			Handler:       _DumpService_CreateDumpCustAddInfoGroup_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "CreateDumpCustAddInfoList",
			Handler:       _DumpService_CreateDumpCustAddInfoList_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "CreateDumpCustAddInfoGroupNeed",
			Handler:       _DumpService_CreateDumpCustAddInfoGroupNeed_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "CreateDumpCustAddInfo",
			Handler:       _DumpService_CreateDumpCustAddInfo_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "CreateDumpMutualFund",
			Handler:       _DumpService_CreateDumpMutualFund_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "CreateDumpReferencesDetails",
			Handler:       _DumpService_CreateDumpReferencesDetails_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "CreateDumpCenterWorker",
			Handler:       _DumpService_CreateDumpCenterWorker_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "CreateDumpWriteoff",
			Handler:       _DumpService_CreateDumpWriteoff_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "CreateDumpAccounts",
			Handler:       _DumpService_CreateDumpAccounts_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "CreateDumpJnlDetails",
			Handler:       _DumpService_CreateDumpJnlDetails_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "CreateDumpJnlHeaders",
			Handler:       _DumpService_CreateDumpJnlHeaders_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "CreateDumpLedgerDetails",
			Handler:       _DumpService_CreateDumpLedgerDetails_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "CreateDumpUsersList",
			Handler:       _DumpService_CreateDumpUsersList_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "CreateDumpMultiplePaymentReceipt",
			Handler:       _DumpService_CreateDumpMultiplePaymentReceipt_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "CreateDumpInActiveCID",
			Handler:       _DumpService_CreateDumpInActiveCID_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "CreateDumpLnBeneficiary",
			Handler:       _DumpService_CreateDumpLnBeneficiary_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "CreateDumpReactivateWriteoff",
			Handler:       _DumpService_CreateDumpReactivateWriteoff_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "CreateDumpColSht",
			Handler:       _DumpService_CreateDumpColSht_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "GetDumpColSht",
			Handler:       _DumpService_GetDumpColSht_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "esystemdump_service.proto",
}
